### ISSUE TITLE
When I was running according to your colab in my jupyter notebook, I met a problem in the step of %load_ext rpy2.ipython, may I ask how to solve this problem and what does it mean?

### ISSUE THREAD

**Issue by yangyouxi123456** [ashrafalaghbari/GA-TCN-LSTM#1]
![image](https://github.com/ashrafalaghbari/GA-TCN-LSTM/assets/126152393/f68d20f5-7a98-4422-b3c8-031ab9f7d881)
![image](https://github.com/ashrafalaghbari/GA-TCN-LSTM/assets/126152393/887d5688-167e-44e8-88f9-b8d552850e76)

**Comment by ashrafalaghbari** [comment]
Hi! 
In order to run R code in Jupyter Notebook, you need to install the rpy2 package. You can do this by running the following command in a code cell within your Jupyter Notebook:

```python
!pip install rpy2 --quiet
```

**Comment by yangyouxi123456** [comment]
收到！
