### ISSUE TITLE
In my opinion, the TCN structure is different from the original paper. The time window is fixed and the dilated convolution is not reflected.

### ISSUE THREAD

**Issue by mistephan** [ashrafalaghbari/GA-TCN-LSTM#3]
In my opinion, the TCN structure is different from the original paper. The time window is fixed and the dilated convolution is not reflected.The time window is fixed at 2 or 4, and dilation_size is always 1. It only uses 1d convolution to extract features and does not increase the range of the receptive field. I don't think this is really a TCN structure. is that so?

**Comment by ashrafalaghbari** [comment]
Thank you for your feedback.  I'd like to address your concerns regarding the TCN structure and its deviation from the original paper.

You are correct that the modifications resulted in a different structure compared to the original Temporal Convolutional Network (TCN) as described in the paper. However, the primary goal of these modifications was to address the needs of my particular application, where a fixed window size and a lack of dilation produced better results. While this does diverge from the canonical TCN design, it was a deliberate choice based on experimental outcomes.
